---
- name: Ensure dependencies are installed ...
  yum: >
    name={{item}}
    state=latest
  with_items:
    - curl
    - git

- name: Add Jenkins repo ...
  get_url: >
    url={{jenkinsRepoUrl}}
    dest=/etc/yum.repos.d/jenkins.repo

- name: Add Jenkins repo GPG key ...
  rpm_key: >
    state=present
    key={{jenkinsRepoKey}}

- name: Install Jenkins ...
  yum: >
    name=jenkins
    state=latest
  register: jenkinsInstallPackage
