---
- name: Remove default Nginx config ...
  file: >
    path=/etc/nginx/sites-enabled/default state=absent

- name: Copy configuration into place ...
  template: >
    src=vhost.j2
    dest=/etc/nginx/sites-enabled/{{item.name}}.conf
  with_items: "{{balancer_vhosts}}"
  notify: restart nginx

- name: Enable nginx service ...
  service: >
    name=nginx
    state=started
    enabled=yes
