# Installs and configure nginx as a load balancer
---
- name: Include OS-specific variables ...
  include_vars: "{{ ansible_os_family }}.yml"
  when: ansible_distribution != 'Ubuntu' and ansible_distribution != 'CentOS'

- name: Include version-specific variables for Ubuntu and CentOS...
  include_vars: "{{ansible_distribution}}.yml"
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'CentOS'

# Install tasks
- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

# Config tasks
- include: config.yml
