---
- name: Install Nginx Repo ...
  yum_repository:
    name: nginx
    description: Official Nginx Repository
    baseurl: "{{nginxRepoUrl}}"
    gpgcheck: no

- name: Install nginx ...
  yum: >
    name=nginx
    state=latest
    update_cache=yes
