---
- name: Include OS-specific variables ...
  include_vars: "{{ ansible_os_family }}.yml"
  when: ansible_distribution != 'Ubuntu'

- name: Include version-specific variables for Ubuntu ...
  include_vars: "{{ansible_distribution}}.yml"
  when: ansible_distribution == 'Ubuntu'
  
# Install tasks
- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'
