---
- name: Installing repo for Java 8 ...
  apt_repository: >
    repo={{javaRepoUrl}}

- name: Update apt cache ...
  apt: >
    update_cache=yes
    cache_valid_time=86400

- name: Install Java JDK ...
  apt: >
    name={{item}}
    state=latest
  with_items: "{{javaPackages}}"
